// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin" | "/admin/activity" | "/admin/ai-usage" | "/admin/api-keys" | "/admin/settings" | "/admin/system" | "/admin/teams" | "/admin/users" | "/ai-chat" | "/brainstorm" | "/brainstorm/[sessionId]" | "/calendar" | "/dashboard" | "/diagrams" | "/diagrams/[diagramId]" | "/docs" | "/forgot-password" | "/goals" | "/join/[token]" | "/login" | "/meetings" | "/notes" | "/notifications" | "/notulen" | "/projects" | "/projects/[projectId]" | "/register" | "/reset-password" | "/settings" | "/settings/ai-keys" | "/settings/team" | "/sprints" | "/tasks"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/admin/activity": {}
  "/admin/ai-usage": {}
  "/admin/api-keys": {}
  "/admin/settings": {}
  "/admin/system": {}
  "/admin/teams": {}
  "/admin/users": {}
  "/ai-chat": {}
  "/brainstorm": {}
  "/brainstorm/[sessionId]": { "sessionId": string; }
  "/calendar": {}
  "/dashboard": {}
  "/diagrams": {}
  "/diagrams/[diagramId]": { "diagramId": string; }
  "/docs": {}
  "/forgot-password": {}
  "/goals": {}
  "/join/[token]": { "token": string; }
  "/login": {}
  "/meetings": {}
  "/notes": {}
  "/notifications": {}
  "/notulen": {}
  "/projects": {}
  "/projects/[projectId]": { "projectId": string; }
  "/register": {}
  "/reset-password": {}
  "/settings": {}
  "/settings/ai-keys": {}
  "/settings/team": {}
  "/sprints": {}
  "/tasks": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }
}
